// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVtHaT_kSrgUDj0JGrrGsVTAmlHl2_wc',
    appId: '1:562012238114:web:907996017203ae06fbb57b',
    messagingSenderId: '562012238114',
    projectId: 'audio-x',
    authDomain: 'audio-x.firebaseapp.com',
    storageBucket: 'audio-x.firebasestorage.app',
    measurementId: 'G-SG4K354B0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACtY8f2eXcAKsZMGgDh_1_aKP9aDakQE',
    appId: '1:562012238114:android:8e52168576686719fbb57b',
    messagingSenderId: '562012238114',
    projectId: 'audio-x',
    storageBucket: 'audio-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACnFtuUUIhbS64AWWvsHor1hdH0EGzUIU',
    appId: '1:562012238114:ios:5c6e4ff5ae726382fbb57b',
    messagingSenderId: '562012238114',
    projectId: 'audio-x',
    storageBucket: 'audio-x.firebasestorage.app',
    androidClientId: '562012238114-b28tekkbsb6683i9ubi0rf56k7tkgvsh.apps.googleusercontent.com',
    iosClientId: '562012238114-t6oub8ob5vf7t1apil3r3jpbb21ga89j.apps.googleusercontent.com',
    iosBundleId: 'com.example.audiox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACnFtuUUIhbS64AWWvsHor1hdH0EGzUIU',
    appId: '1:562012238114:ios:5c6e4ff5ae726382fbb57b',
    messagingSenderId: '562012238114',
    projectId: 'audio-x',
    storageBucket: 'audio-x.firebasestorage.app',
    androidClientId: '562012238114-b28tekkbsb6683i9ubi0rf56k7tkgvsh.apps.googleusercontent.com',
    iosClientId: '562012238114-t6oub8ob5vf7t1apil3r3jpbb21ga89j.apps.googleusercontent.com',
    iosBundleId: 'com.example.audiox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVtHaT_kSrgUDj0JGrrGsVTAmlHl2_wc',
    appId: '1:562012238114:web:7807fee7e04d1920fbb57b',
    messagingSenderId: '562012238114',
    projectId: 'audio-x',
    authDomain: 'audio-x.firebaseapp.com',
    storageBucket: 'audio-x.firebasestorage.app',
    measurementId: 'G-HF437HJNL5',
  );
}
